package com.auction.network;

import java.io.Serializable;

public enum MessageType implements Serializable {
    LOGIN_REQUEST, LOGIN_RESPONSE,
    SIGNUP_REQUEST, SIGNUP_RESPONSE,
    LOGOUT_REQUEST, LOGOUT_RESPONSE,

    GET_ALL_AUCTIONS_REQUEST, GET_ALL_AUCTIONS_RESPONSE,

    // ĐÂY CHÍNH LÀ 2 LỆNH GIÚP BẠN HẾT BÁO ĐỎ
    GET_ITEM_DETAILS_REQUEST, GET_ITEM_DETAILS_RESPONSE,

    ADD_ITEM_REQUEST, ADD_ITEM_RESPONSE,
    EDIT_ITEM_REQUEST, EDIT_ITEM_RESPONSE,
    DELETE_ITEM_REQUEST, DELETE_ITEM_RESPONSE,
    GET_MY_ITEMS_REQUEST, GET_MY_ITEMS_RESPONSE,

    CREATE_AUCTION_REQUEST, CREATE_AUCTION_RESPONSE,
    CANCEL_AUCTION_REQUEST, CANCEL_AUCTION_RESPONSE,
    GET_MY_AUCTIONS_REQUEST, GET_MY_AUCTIONS_RESPONSE,

    JOIN_AUCTION_REQUEST, JOIN_AUCTION_RESPONSE,
    LEAVE_AUCTION_REQUEST, LEAVE_AUCTION_RESPONSE,

    PLACE_BID_REQUEST, PLACE_BID_RESPONSE,
    SET_AUTO_BID_REQUEST, SET_AUTO_BID_RESPONSE,
    GET_MY_BIDS_REQUEST, GET_MY_BIDS_RESPONSE,

    AUCTION_UPDATE_NOTIFICATION, CHAT_MESSAGE_NOTIFICATION,
    USER_BANNED_NOTIFICATION, USER_BALANCE_UPDATE_NOTIFICATION,
    AUCTION_STARTED_NOTIFICATION, AUCTION_ENDED_NOTIFICATION,

    ADMIN_ACTION_REQUEST, ADMIN_ACTION_RESPONSE,
    PING, PONG
}