package com.auction.network;

import java.io.Serializable;

public enum MessageType implements Serializable {
    //Auth
    LOGIN_REQUEST, LOGIN_RESPONSE,
    SIGNUP_REQUEST, SIGNUP_RESPONSE,
    LOGOUT_REQUEST, LOGOUT_RESPONSE,

    //General details
    GET_ALL_AUCTIONS_REQUEST, GET_ALL_AUCTIONS_RESPONSE,

    GET_ITEM_DETAILS_REQUEST, GET_ITEM_DETAILS_RESPONSE,

    //Items
    ADD_ITEM_REQUEST, ADD_ITEM_RESPONSE,
    EDIT_ITEM_REQUEST, EDIT_ITEM_RESPONSE,
    DELETE_ITEM_REQUEST, DELETE_ITEM_RESPONSE,
    GET_MY_ITEMS_REQUEST, GET_MY_ITEMS_RESPONSE,

    //Auctions
    CREATE_AUCTION_REQUEST, CREATE_AUCTION_RESPONSE,
    CANCEL_AUCTION_REQUEST, CANCEL_AUCTION_RESPONSE,
    GET_MY_AUCTIONS_REQUEST, GET_MY_AUCTIONS_RESPONSE,

    JOIN_AUCTION_REQUEST, JOIN_AUCTION_RESPONSE,
    LEAVE_AUCTION_REQUEST, LEAVE_AUCTION_RESPONSE,

    //Bids
    PLACE_BID_REQUEST, PLACE_BID_RESPONSE,
    SET_AUTO_BID_REQUEST, SET_AUTO_BID_RESPONSE,
    GET_MY_BIDS_REQUEST, GET_MY_BIDS_RESPONSE,

    //server broadcast - admin actions
    AUCTION_UPDATE_NOTIFICATION, CHAT_MESSAGE_NOTIFICATION,
    USER_BANNED_NOTIFICATION, USER_BALANCE_UPDATE_NOTIFICATION,
    AUCTION_STARTED_NOTIFICATION, AUCTION_ENDED_NOTIFICATION,

    GET_ALL_USERS_REQUEST, GET_ALL_USERS_RESPONSE,
    CREATE_USER_REQUEST, CREATE_USER_RESPONSE,
    UPDATE_USER_REQUEST, UPDATE_USER_RESPONSE,
    DELETE_USER_REQUEST ,DELETE_USER_RESPONSE,
    UPDATE_BALANCE_REQUEST, UPDATE_BALANCE_RESPONSE,
    ADMIN_DELETE_AUCTION_REQUEST, ADMIN_DELETE_AUCTION_RESPONSE,
    ADMIN_UPDATE_AUCTION_REQUEST, ADMIN_UPDATE_AUCTION_RESPONSE,

    ADMIN_ACTION_REQUEST, ADMIN_ACTION_RESPONSE,
    PING, PONG
}